### ISSUE TITLE
Is there a way to run bitgod as a daemon

### ISSUE THREAD

**Issue by tkembo** [BitGo/bitgod#1]
How can I run the `bitgod -env prod` command & have bitgod run in the background as a daemon?

**Comment by tomtruitt** [comment]
No one ever answered this? My assumption is the "d" in bitgod stands for daemon. Maybe you are asking how to logout with the process being killed?

**Comment by tomtruitt** [comment]
I had a question too but can't wait years for it to be answered...

**Comment by tkembo** [comment]
I managed to get it to run as a daemon by running the following command:

`$ nohup bitgod -env prod &`

I know there may be other ways but that's what worked for me

**Comment by tomtruitt** [comment]
Lol yes that is the recommended way. It's just discouraging that no one ever answered you.

**Comment by tkembo** [comment]
They do respond to support emails very fast though so that may be a better way to get help. You mentioned you had a question too?

**Comment by tomtruitt** [comment]
Regarding payment protocol support. Bitpay has a comparison chart that reports bitgo wallets having partial support but doesn't elaborate on what that is. Also the marketing doesn't suggest the both sender and receiver need to have a bitgo wallet for instant payments but the documentation seems to suggest they do. If I need to issue bitgo wallets to my customers for them to pay me and get instant receipts (necessary for my business logic) then I need to make sure I can receive refund addresses from them. Lol the simple things that are a part of normal transactions that get complex in Bitcoin

**Comment by tkembo** [comment]
Hmnnn, I don't have much experience with that to help. Hey, you could ask that in their slack channel ( slack.bitgo.com ) - there's almost always someone who can help there.

**Comment by tomtruitt** [comment]
Nice thanks!

**Comment by bpdavenport** [comment]
Sorry for not responding here -- as some other commenters said, devsupport@bitgo.com or our slack are your best options.
