### ISSUE TITLE
bitgo.com bch wallet

### ISSUE THREAD

**Issue by corehook** [BitGo/bitgod#10]
Alloha!
I try to use bitgod with bch wallet id, but getting error : 
```zsh
deployer @ app ➜ bitcoin-cli -rpcport=9332 setwallet 5a320e714054ad371affca98a47bed1f
error code: -32603
error message:
Error: invalid wallet id
```
But bitgo api v2 allows you to work with a bch wallet. 
How i can use BCH wallet with bitgod ?

**Comment by corehook** [comment]
@lrvick @ryanxcharles @bencxr @OttoAllmendinger @jlopp  guys please help me

**Comment by jlopp** [comment]
I'm not aware of any plans to add BCH support to BitGoD.

**Comment by Xekyo** [comment]
bitgod only supports V1 BTC.
