### ISSUE TITLE
Problem setting wallet

### ISSUE THREAD

**Issue by tkembo** [BitGo/bitgod#2]
I have a BitGo wallet, I have create a token, I have been able to successfully authenticate with ```bitcoin-cli -rpcport=19332 settoken``` but when I try to set the wallet using ```bitcoin-cli -rpcport=19332 setwallet``` I get the following error:

```error: {"code":-32603,"message":"Error: not found"}```

Any idea why I'm getting this error or what the problem could be?

**Comment by bencxr** [comment]
Set wallet expects a walletid. Did you provide that and is the wallet accessible from the account that you created the token for?

**Comment by tkembo** [comment]
It worked. I got the wallet id from the URL. Many thanks

**Comment by poseidon-j** [comment]
i got error  error code: -32603
error message:
Error: invalid wallet id

**Comment by Xekyo** [comment]
@poseidon-j: Is the wallet a V1 wallet? BitGoD only connects to the V1 plaform. If you created the wallet recently, it would be a V2 wallet instead, and not compatible with BitGoD.

**Comment by poseidon-j** [comment]
> @poseidon-j: Is the wallet a V1 wallet? BitGoD only connects to the V1 plaform. If you created the wallet recently, it would be a V2 wallet instead, and not compatible with BitGoD.

Which method can I follow for v2. Yes I’m using recent one it’s v2.

**Comment by Xekyo** [comment]
We don't offer a full node wrapper for v2, but you can find our SDK including an Express server here: https://www.npmjs.com/package/bitgo

**Comment by poseidon-j** [comment]
thank you
