### ISSUE TITLE
Other currencies support

### ISSUE THREAD

**Issue by ashanaakh** [BitGo/bitgod#26]
How can I use `bitgod` with other currencies, like BCH

**Comment by thomas4019** [comment]
Hi @ashanaakh, it's currently not possible to use bitgod with coins other than BCH and support is not likely to be added soon. For that you would use our [JavaScript SDK or API](https://www.bitgo.com/api/v2/).

**Comment by ashanaakh** [comment]
@thomas4019 thanks, I think you mean other that `BTC`, not `BCH ` ? 😄

**Comment by thomas4019** [comment]
Yep, my mistake. Only BTC is supported in bitgod.
