### ISSUE TITLE
I'm having trouble accessing bitgod remotely

### ISSUE THREAD

**Issue by tkembo** [BitGo/bitgod#3]
I am trying to access a bitgod installation that is on a remote server. Is there a line I have to add to my configuration file to make bitgod accessible remotely?
I have tried to access it with the following command:
```
curl --user <user> --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' <ip address:port>
```

**Comment by bencxr** [comment]
hi tkembo, please try to run it with arguments:
-rpcbind <address to listen on>
for example, 0.0.0.0 to listen on all addresses.

**Comment by tkembo** [comment]
Thanks. I've done that and I am now getting the following output after running the same command:
```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Unauthorized"},"id":null}
```

Is that normal? Why does it say Unauthorized?

**Comment by bencxr** [comment]
you need to use the rpc username and password (see rpc spec). 
how are you using bitgod? it's typically used with bitcoin-cli or bitcoin rpc libraries.

**Comment by tkembo** [comment]
yes we are using it with bitcoin-cli. We are using it for our bitcoin exchange (https://medium.com/@benedictchan/building-the-world-s-first-open-source-multi-sig-bitcoin-exchange-a6f1221eff46)[https://medium.com/@benedictchan/building-the-world-s-first-open-source-multi-sig-bitcoin-exchange-a6f1221eff46] but we have now decided to move bitgod, bitcoind & RabbitMQ to a separate EC2 instance. So I was having trouble accessing bitgod remotely

**Comment by tkembo** [comment]
It's working now. I suspect my problem was using a special character for the password
